# Install amazon cloudwatch agent
- name: Check if amazon cloudwatch agent (cwa) is installed
  stat:
    path: /opt/aws/amazon-cloudwatch-agent
  register: aws_cwa_path
  changed_when: false

- name: Install cwa dependent packages
  apt: pkg={{item}} state=present update-cache=yes
  with_items:
    - unzip

- block:
  - name: cwa - make temp dir for installation files
    file:
      path: "/tmp/aws-cwa-install"
      state: "directory"
  - name: cwa - download & unpack the latest cloudwatch agent .zip
    unarchive:
      remote_src: "yes"
      src: "https://s3.amazonaws.com/amazoncloudwatch-agent/linux/amd64/latest/AmazonCloudWatchAgent.zip"
      dest: "/tmp/aws-cwa-install/"
  - name: cwa - run the installer
    shell: dpkg -i -E /tmp/aws-cwa-install/amazon-cloudwatch-agent.deb
    notify: restart amazon-cloudwatch-agent
  - name: cwa - remove temp dir
    file:
      path: "/tmp/aws-cwa-install/"
      state: "absent"
  when: aws_cwa_path.stat.exists != True

# Template is generated by running
# '/opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-config-wizard'
# per
# https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/create-cloudwatch-agent-configuration-file-wizard.html
- name: Install amazon cloudwatch config
  template:
    src: amazon-cloudwatch-agent.json.j2
    dest: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
    mode: 0644
    owner: root
    group: root
  register: cloudwatch_config

- name: restart amazon-cloudwatch-agent
  service:
    name: amazon-cloudwatch-agent
    state: restarted
  when: cloudwatch_config.changed
  changed_when: False

- name: Verify that amazon-cloudwatch-agent is actually running
  command: systemctl is-active --quiet amazon-cloudwatch-agent
