- name: update hostname file
  copy:
    dest: /etc/hostname
    owner: root
    group: root
    mode: 0644
    content: "{{inventory_hostname}}"
  register: etc_hostname

- name: set hostname
  command: hostname -F /etc/hostname
  when: etc_hostname.changed

- name: "Build hosts file"
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: "{{ hostvars[item].ansible_default_ipv4.address }} {{item}}"
    state: present
  with_items: "{{ groups['all'] }}"

- name: Install base packages
  apt: pkg={{item}} state=present update-cache=yes
  with_items:
    - build-essential
    - htop
    - libldap2-dev
    - libpq-dev
    - libsasl2-dev
    - libyaml-dev
    - mailutils
    - postfix
    - postgresql-client
    - python3
    - python3-dev
    - python-httplib2
    - python-psycopg2
    - python-virtualenv

- include_role:
    name: base
    tasks_from: systemd_journal_remote_server.yml
  when: 'upgrade_only is not defined and master_node'

- include_role:
    name: base
    tasks_from: systemd_journal_remote_node.yml
  when: 'upgrade_only is not defined and not master_node'

- include_role:
    name: base
    tasks_from: postfix.yml
  when: 'upgrade_only is not defined and ec2_smtp_server is defined'
