- name: Install base packages
  apt: pkg={{item}} state=installed update-cache=yes
  with_items:
    - build-essential
    - mailutils
    - postgresql-client
    - postfix
    - python3
    - python3-dev
    - python-virtualenv
    - python-psycopg2
    - python-httplib2
    - libpq-dev
    - libldap2-dev
    - libsasl2-dev
    - libyaml-dev

- include_tasks: postfix.yml
  when: 'upgrade_only is not defined and ec2_smtp_server is defined'
