- name: Install base packages
  apt: pkg={{item}} state=installed update-cache=yes
  with_items:
    - build-essential
    - python3
    - python3-dev
    - python-virtualenv
    - python-psycopg2
    - python-httplib2
    - libpq-dev
    - libldap2-dev
    - libsasl2-dev
    - libyaml-dev

