- include_role:
    name: frontend
    tasks_from: setup.yml
  when: upgrade_only is not defined

- include_role:
    name: frontend
    tasks_from: skip_setup.yml
  when: upgrade_only is defined

- command: sudo -u squad env -i bash -l -c '{{install_base}}/bin/squad-admin collectstatic --no-input -v 0'
  name: collect static files
  when: install_squad.changed
  changed_when: False

- shell: 'if systemctl is-active squad.service; then systemctl reload squad.service; else systemctl restart squad.service; fi'
  name: start/reload squad
  when: squad_service.changed or install_squad.changed or settings.changed or linaro_ldap_backends.changed or secret.changed
  changed_when: False
  notify: reload-apache2

- shell: systemctl restart squad.service
  name: restart squad
  when: environmentfile.changed  or install_squad_linaro_plugins.changed
  changed_when: False
  notify: reload-apache2

- name: Configure singleton services
  when: master_node
  include_role:
    name: master
