- name: Install webserver packages
  apt: pkg={{item}} state=installed update-cache=yes
  with_items:
    - apache2

- name: Enable required apache2 modules
  command: a2enmod proxy proxy_balancer lbmethod_byrequests proxy_http rewrite ssl cgid headers
  register: result
  changed_when: "'Enabling module' in result.stdout"
  notify: restart-apache2

- name: systemd service - web
  template:
    src: roles/frontend/templates/squad.service
    dest: /etc/systemd/system/squad.service
  notify: reload-systemd
  register: squad_service

- command: systemctl enable squad.service
  changed_when: False

- command: sudo -u squad env -i bash -l -c '{{install_base}}/bin/squad-admin collectstatic --no-input -v 0'
  name: collect static files
  when: install_squad.changed
  changed_when: False

- shell: 'if systemctl is-active squad.service; then systemctl reload squad.service; else systemctl restart squad.service; fi'
  name: start/reload squad
  when: squad_service.changed or install_squad.changed or settings.changed or linaro_ldap_backends.changed
  changed_when: False
  notify: reload-apache2

- shell: systemctl restart squad.service
  name: restart squad
  when: environmentfile.changed  or install_squad_linaro_plugins.changed
  changed_when: False
  notify: reload-apache2

- file:
    path: "{{install_base}}/www"
    owner: root
    group: root
    mode: 0555
    state: directory

- name: apache2 config
  template:
    src: roles/frontend/templates/apache2.conf
    dest: /etc/apache2/sites-available/{{inventory_hostname}}.conf
  notify: reload-apache2

- command: a2ensite {{inventory_hostname}}
  register: result
  changed_when: "'Enabling site' in result.stdout"
  notify: reload-apache2

- name: Configure singleton services
  when: master_node
  include_role:
    name: master
