- name: Install webserver packages
  apt: pkg={{item}} state=installed update-cache=yes
  with_items:
    - apache2

- name: Enable required apache2 modules
  command: a2enmod proxy proxy_balancer lbmethod_byrequests proxy_http rewrite ssl cgid headers
  register: result
  changed_when: "'Enabling module' in result.stdout"
  notify: restart-apache2

- name: calculate number of workers
  shell: 'echo $(($(nproc)*2 + 1))'
  register: number_of_workers_results
  changed_when: False

- name: number of workers
  set_fact:
    number_of_workers: "{{number_of_workers_results.stdout}}"

- name: systemd service - web
  template:
    src: roles/frontend/templates/squad.service
    dest: /etc/systemd/system/squad.service
  notify: reload-systemd
  register: squad_service

- meta: flush_handlers

- command: systemctl enable squad.service
  changed_when: False

- file:
    path: "{{install_base}}/www"
    owner: root
    group: root
    mode: 0555
    state: directory

- name: apache2 config
  template:
    src: roles/frontend/templates/apache2.conf
    dest: /etc/apache2/sites-available/{{inventory_hostname}}.conf
  notify: reload-apache2

- name: disable default apache site
  command: a2dissite 000-default.conf
  register: result
  when: 'inventory_hostname == "qa-reports-master.local"'
  changed_when: "'Site 000-default disabled.' in result.stdout"
  notify: reload-apache2

- command: a2ensite {{inventory_hostname}}
  register: result
  changed_when: "'Enabling site' in result.stdout"
  notify: reload-apache2
