---
- name: Configure service
  hosts: all
  roles:
    - base
    - squad
    - squad-lava-listener
    - kernelci-monitor
  handlers:
    - name: reload-systemd
      command: systemctl daemon-reload
    - name: reload-apache2
      command: systemctl reload apache2
