#!/bin/sh

basedir=$(dirname $0)
passwd_file=$basedir/secrets/vault.gpg

if [ ! -f $passwd_file ]; then
  # create a new password file
  openssl rand -hex 32 | gpg --encrypt --output $passwd_file
fi

for file in $passwd_file $basedir/secrets/vault-*.gpg; do
  if gpg --quiet --batch --use-agent --decrypt $file 2>/dev/null; then
    exit
  fi
done
