- name: ensure apache2 is installed
  apt:
    pkg:
      - apache2

########################################################################
# TODO: remove these lines when Ubuntu has proper dehydrated packages
########################################################################
- name: copy dehydrated .deb
  copy:
    src: roles/ssl/files/dehydrated_0.3.1-2_all.deb
    dest: /root/dehydrated_0.3.1-2_all.deb

- name: copy dehydrated-apache2 .deb
  copy:
    src: roles/ssl/files/dehydrated-apache2_0.3.1-2_all.deb
    dest: /root/dehydrated-apache2_0.3.1-2_all.deb

- name: install dehydrated
  command: dpkg -i /root/dehydrated_0.3.1-2_all.deb
  args:
    creates: /usr/bin/dehydrated

- name: install dehydrated-apache2
  command: dpkg -i /root/dehydrated-apache2_0.3.1-2_all.deb
  args:
    creates: /etc/apache2/conf-available/dehydrated.conf
########################################################################

- name: install SSL packages
  apt:
    pkg:
      - dehydrated
      - dehydrated-apache2
    state: installed
    update-cache: yes

- name: domains file for dehydrated
  copy:
    src: roles/ssl/files/domains.txt.{{inventory_hostname}}
    dest: /etc/dehydrated/domains.txt

- name: service to create/renew SSL certificate
  copy:
    src: roles/ssl/files/dehydrated.service
    dest: /etc/systemd/system/dehydrated.service

- name: timer to create/renew SSL certificate
  copy:
    src: roles/ssl/files/dehydrated.timer
    dest: /etc/systemd/system/dehydrated.timer

- name: enable dehydrated timer
  shell: 'systemctl daemon-reload && systemctl enable dehydrated.timer && systemctl start dehydrated.timer'

- name: run dehydrated
  command: 'systemctl start dehydrated.service'
