#
# Deploy one qareports container for squad-scheduler
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qareports-scheduler-deployment
  labels:
    app: qareports-scheduler

spec:
  replicas: 1
  selector:
    matchLabels:
      app: qareports-scheduler

  template:
    metadata:
      labels:
        app: qareports-scheduler

    spec:
      volumes:
      - name: qareports-secret-key
        configMap:
          name: qareports-secret-key

      containers:
      - name: qareports-scheduler
        image: squadproject/squad:release
        imagePullPolicy: "Always"
        command: ["sh", "-c"]
        args:
        - squad-scheduler --schedule=/app/celerybeat-schedule.db

        envFrom:
        - secretRef:
            name: qareports-environment

        volumeMounts:
        - name: qareports-secret-key
          mountPath: /app/secret.dat
          subPath: secret.dat

        resources:
          requests:
            memory: "128M"
            cpu: "250m"

          limits:
            memory: "512M"
            cpu: "500m"
