#
# Autoscale pods to have minumum of 2 pods up to 10 pods
# depending on CPU average load
#
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: qareports-web-autoscale
spec:
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 15
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: qareports-web-deployment

---

#
# Apache configuration
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: qareports-web-apache-conf
data:
  qareports.conf: |-
    # Load some mods
    LoadModule cgid_module modules/mod_cgid.so
    LoadModule deflate_module modules/mod_deflate.so
    LoadModule filter_module modules/mod_filter.so
    LoadModule lbmethod_byrequests_module modules/mod_lbmethod_byrequests.so
    LoadModule proxy_module modules/mod_proxy.so
    LoadModule proxy_http_module modules/mod_proxy_http.so
    LoadModule proxy_balancer_module modules/mod_proxy_balancer.so
    LoadModule slotmem_shm_module modules/mod_slotmem_shm.so
    LoadModule vhost_alias_module modules/mod_vhost_alias.so
    LoadModule rewrite_module modules/mod_rewrite.so

    # Configure mod_deflate
    # these are known to be safe with MSIE 6
    AddOutputFilterByType DEFLATE text/html text/plain text/xml

    # everything else may cause problems with MSIE 6
    AddOutputFilterByType DEFLATE text/css
    AddOutputFilterByType DEFLATE application/x-javascript application/javascript application/ecmascript application/json
    AddOutputFilterByType DEFLATE application/rss+xml
    AddOutputFilterByType DEFLATE application/xml

    # Virtual host setup
    <VirtualHost *:80>
      ProxyPreserveHost On

      RewriteEngine On

      # http -> https
      RewriteCond %{HTTP:X-Forwarded-Proto} =http
      RewriteRule .* https://%{HTTP:Host}%{REQUEST_URI} [L,R=permanent]

      # Security headers
      Header always set Strict-Transport-Security "max-age=31536000; includeSubdomains;"
      Header always set X-Content-Type-Options "nosniff;"
      Header always set Content-Security-Policy "default-src 'none'; script-src 'self' 'unsafe-inline'; connect-src 'self'; img-src 'self' www.gravatar.com; style-src 'self' 'unsafe-inline'; font-src 'self';"

      # Set default cache controll if there isn't any
      Header setIfEmpty Cache-Control "no-cache"

      # Serve static files separately
      Alias /static "/qareports_static/static"
      <Directory "/qareports_static/static">
        Require all granted
      </Directory>

      # Pass routing to gunicorn
      ProxyPassMatch ^/static !
      ProxyPass "/" http://127.0.0.1:8000/
    </VirtualHost>

---

#
# Deploy initially one pod of qareports-web container
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qareports-web-deployment
  labels:
    app: qareports-web

spec:
  replicas: 1
  selector:
    matchLabels:
      app: qareports-web

  template:
    metadata:
      labels:
        app: qareports-web

    spec:
      serviceAccount: qareports-serviceaccount
      securityContext:
        fsGroup: 0

      initContainers:
      - name: init-qareports-web
        image: squadproject/squad:release
        imagePullPolicy: "Always"
        command: ["cp", "-r", "/app/static", "/qareports_static"]
        volumeMounts:
        - name: static-files
          mountPath: /qareports_static

      containers:
      - name: apache2
        image: httpd:2.4
        command: ["sh", "-c"]
        args:
        - cat qareports.conf >> conf/httpd.conf && httpd -D FOREGROUND

        ports:
        - containerPort: 80

        volumeMounts:
        - name: qareports-web-apache-conf
          mountPath: /usr/local/apache2/qareports.conf
          subPath: qareports.conf

        - name: static-files
          mountPath: /qareports_static

        resources:
          requests:
            memory: "128M"
            cpu: "250m"

          limits:
            memory: "512M"
            cpu: "500m"

      - name: qareports-web
        image: squadproject/squad:release
        imagePullPolicy: "Always"
        command: ["sh", "-c"]
        args:
        - squad --timeout=60 --workers=8 --fast --log-level DEBUG

        envFrom:
        - secretRef:
            name: qareports-environment

        # Inject ldap into container
        env:
        - name: SQUAD_EXTRA_SETTINGS
          value: "/app/linaro_ldap.py"

        volumeMounts:
        - name: qareports-secret-key
          mountPath: /app/secret.dat
          subPath: secret.dat

        - name: qareports-ldap-conf
          mountPath: /app/linaro_ldap.py
          subPath: linaro_ldap.py

        - name: qareports-ldap-conf
          mountPath: /usr/local/lib/python3.7/dist-packages/linaro_ldap_backends.py
          subPath: linaro_ldap_backends.py

        - name: qareports-local-settings
          mountPath: /usr/local/lib/python3.7/dist-packages/squad/local_settings.py
          subPath: local_settings.py

        resources:
          requests:
            memory: "1024M"
            cpu: "2"

          limits:
            memory: "4096M"
            cpu: "2"

      volumes:
      - name: qareports-secret-key
        configMap:
          name: qareports-secret-key

      - name: qareports-web-apache-conf
        configMap:
          name: qareports-web-apache-conf

      - name: qareports-ldap-conf
        configMap:
          name: qareports-ldap-conf

      - name: qareports-local-settings
        configMap:
          name: qareports-local-settings

      - name: static-files
        emptyDir: {}
