apiVersion: v1
kind: Pod
metadata:
  name: qareports-pod-name
  labels:
    app: qareports-pod

spec:
  serviceAccountName: qareports-serviceaccount
  securityContext:
    fsGroup: 0

  volumes:
  - name: qareports-local-settings
    configMap:
      name: qareports-local-settings

  containers:
  - name: qareports-pod
    image: squadproject/squad:release
    securityContext:
      allowPrivilegeEscalation: false
      runAsUser: 0
    imagePullPolicy: "Always"
    command: ["sh", "-c"]
    args:
    - sleep infinity

    envFrom:
    - secretRef:
        name: qareports-environment

    volumeMounts:
    - name: qareports-local-settings
      mountPath: /usr/local/lib/python3.7/dist-packages/squad/local_settings.py
      subPath: local_settings.py

    resources:
      requests:
        memory: "8192M"
        cpu: "4"

      limits:
        memory: "8192M"
        cpu: "4"
