#
# Autoscale pods to have minumum of 2 pods up to 10 pods
# depending on CPU average load
#
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: qareports-worker-autoscale
spec:
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 15
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: qareports-worker-deployment

---

#
# Deploy initially one pod of qareports container as worker
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qareports-worker-deployment
  labels:
    app: qareports-worker

spec:
  replicas: 1
  selector:
    matchLabels:
      app: qareports-worker

  template:
    metadata:
      labels:
        app: qareports-worker

    spec:
      terminationGracePeriodSeconds: 3600
      serviceAccount: qareports-serviceaccount
      securityContext:
        fsGroup: 0

      volumes:
      - name: qareports-secret-key
        configMap:
          name: qareports-secret-key

      - name: qareports-ssh-key
        secret:
          secretName: qareports-ssh-key

      - name: qareports-local-settings
        configMap:
          name: qareports-local-settings

      - name: qareports-extra-settings
        configMap:
          name: qareports-extra-settings

      - name: ssh-folder
        emptyDir: {}

      initContainers:
      - name: init-qareports-worker
        image: squadproject/squad:release
        imagePullPolicy: "Always"
        command: ["sh", "-c", "cp /app/id_rsa /app/.ssh/id_rsa && chown -R squad:squad /app/.ssh && chmod 0600 /app/.ssh/id_rsa"]
        securityContext:
          runAsUser: 0

        volumeMounts:
        - name: ssh-folder
          mountPath: /app/.ssh

        - name: qareports-ssh-key
          mountPath: /app/id_rsa
          subPath: id_rsa

      containers:
      - name: qareports-worker
        image: squadproject/squad:release
        imagePullPolicy: "Always"
        command: ["squad-worker"]
        args:
        - --exclude-queues=ci_fetch
        - --concurrency=3
        - --max-memory-per-child=1000000
        - --without-mingle
        - --without-gossip

        envFrom:
        - secretRef:
            name: qareports-environment

        # Inject health-check settings
        env:
        - name: SQUAD_EXTRA_SETTINGS
          value: "/app/extra_settings.py"

        volumeMounts:
        - name: qareports-secret-key
          mountPath: /app/secret.dat
          subPath: secret.dat

        - name: qareports-local-settings
          mountPath: /usr/local/lib/python3.9/dist-packages/squad/local_settings.py
          subPath: local_settings.py

        - name: qareports-extra-settings
          mountPath: /app/extra_settings.py
          subPath: extra_settings.py

        - name: ssh-folder
          mountPath: /app/.ssh

        resources:
          requests:
            memory: "1024M"
            cpu: "1"

          limits:
            memory: "2048M"
            cpu: "1"
