#!/bin/sh

# In order to update the people who can decrypt the password
# one must first be able to decrypt it, then encrypt it again
# with the updated list of keys. You should have all keys on
# the local keyring before re-encrypting the vault.
# gpg --encrypt \
#     --recipient amro.hassaan@linaro.org     \
#     --recipient antonio.terceiro@linaro.org \
#     --recipient ben.copeland@linaro.org     \
#     --recipient charles.oliveira@linaro.org \
#     --recipient kelley.spoon@linaro.org     \
#     --recipient luis.tonicha@linaro.org     \
#     <password-file>

basedir=$(dirname $0)
passwd_file=$basedir/../secrets/vault.gpg

if [ ! -f $passwd_file ]
then
  # create a new password file
  openssl rand -hex 32 | gpg --encrypt --output $passwd_file
fi

gpg --quiet --batch --use-agent --decrypt $passwd_file 2>/dev/null
