- name: systemd service - listener
  template:
    src: roles/master/templates/squad-listener.service
    dest: /etc/systemd/system/squad-listener.service
  notify: reload-systemd
  register: squad_listener_service

- meta: flush_handlers

- command: systemctl enable squad-listener.service
  changed_when: False

- name: systemd service - scheduler
  template:
    src: roles/master/templates/squad-scheduler.service
    dest: /etc/systemd/system/squad-scheduler.service
  notify: reload-systemd
  register: squad_scheduler_service

- meta: flush_handlers

- command: systemctl enable squad-scheduler.service
  changed_when: False
