---
- name: Configure service
  hosts: all
  roles:
    - base
    - squad
  handlers:
    - name: reload-systemd
      command: systemctl daemon-reload
    - name: reload-apache2
      command: systemctl reload apache2
    - name: restart-apache2
      command: systemctl reload apache2
