#!/bin/sh

set -eu

if [ $# -lt 1 ]; then
  echo "usage: $0 ENVIRONMENT [HOST]"
  exit 1
fi

env="$1"
shift
host="${1:-}"

inventory=$(dirname $0)/hosts.$env

if [ -n "$host" ]; then
  host=$(grep "ansible_host=" "$inventory" | awk '/^\S*'$host'/ {sub("ansible_host=", "", $2); print($2); exit }')
else
  # no host, assume master
  host=$(awk '/master_node=1/ {sub("ansible_host=", "", $2); print($2)}' "$inventory")
fi

user=$(sed -e '/^ansible_user=/!d; s/ansible_user=//' "$inventory")
ssh_args=$(sed -e '/^ansible_ssh_common_args=/!d; s/^ansible_ssh_common_args="\(.*\)"/\1/' "$inventory")

exec ssh $ssh_args -l "$user" "$host"
