- name: Install PostgreSQL and RabbitMQ
  apt: pkg={{item}} state=present update-cache=yes
  when: master_node
  with_items:
    - postgresql
    - rabbitmq-server

- name: RabbitMQ config
  when: master_node
  template:
    src: roles/squad/templates/rabbitmq.config
    dest: /etc/rabbitmq/rabbitmq.config
  notify: restart-rabbitmq

- name: get PostgreSQL config file
  shell: 'find /etc/postgresql -name postgresql.conf | head -1'
  register: postgresql_conf
  changed_when: false

- name: get PostgreSQL pg_hba.conf
  shell: 'find /etc/postgresql -name pg_hba.conf | head -1'
  register: pg_hba_conf
  changed_when: false

- name: configure PostgreSQL networking
  register: postgresql_networking
  lineinfile:
    dest: '{{postgresql_conf.stdout}}'
    line: "listen_addresses = '*'"

- name: configure pg_hba
  register: pg_hba
  lineinfile:
    dest: '{{pg_hba_conf.stdout}}'
    line: 'host     all             all             samenet                 md5'

- name: restart PostgreSQL
  shell: systemctl restart postgresql
  when: postgresql_networking.changed or pg_hba.changed
  changed_when: false

- name: create database user
  shell: 'sudo -u postgres createuser {{database_user}} || true'
  register: createuser
  changed_when: '"already exists" not in createuser.stderr'

- name: set database password
  shell: |
    sudo -u postgres psql -c "ALTER USER {{database_user}} WITH PASSWORD '{{database_password}}'" || true
  changed_when: false

- name: create database
  shell: 'sudo -u postgres createdb --owner={{database_user}} {{database_name}} || true'
  register: createdb
  changed_when: '"already exists" not in createdb.stderr'
