- include_role:
    name: base
  when: upgrade_only is not defined

- include_tasks: dev.yml
  when: upgrade_only is not defined and master_node and database_is_local is defined

- include_tasks: setup.yml
  when: upgrade_only is not defined

- include_tasks: skip_setup.yml
  when: upgrade_only is defined

- name: Copy squad package, if any
  copy:
    src: "{{squad}}"
    dest: "{{install_base}}/{{squad}}"
    owner: root
    group: root
    mode: 0644
  when: 'squad != "squad"'

- name: Install squad
  command: "{{install_base}}/bin/pip install -U {{squad}}"
  args:
    chdir: '{{install_base}}'
  register: install_squad
  changed_when: "'up-to-date: squad' not in install_squad.stdout"

- name: install Linaro-specific SQUAD plugins
  command: "{{install_base}}/bin/pip install --upgrade --upgrade-strategy=only-if-needed squad-linaro-plugins"
  register: install_squad_linaro_plugins
  changed_when: "'up-to-date: squad-linaro-plugins' not in install_squad_linaro_plugins.stdout"

- command: sudo -u squad env -i bash -l -c '{{install_base}}/bin/squad-admin migrate'
  name: migrate database
  when: 'install_squad.changed and master_node'
  changed_when: False
