########################################################################
### munin setup
########################################################################

- name: Install munin-node
  apt:
    pkg: munin-node
    state: present
    update-cache: yes

- name: munin plugins for squad
  register: munin_squad_plugins
  copy:
    src: munin/{{item}}
    dest: /etc/munin/plugins/{{item}}
    owner: root
    group: root
    mode: 0755
  with_items:
    - squad_processes
    - squad_job_count
    - squad_queue

- name: configure munin plugins for squad
  template:
    src: munin/plugins.conf
    dest: /etc/munin/plugin-conf.d/squad
    owner: root
    group: root
    mode: 0644
  register: munin_squad_plugins_conf

- name: configure munin-node hostname
  register: munin_node_conf_hostname
  lineinfile:
    dest: /etc/munin/munin-node.conf
    line: "host_name {{ inventory_hostname }}"

- name: configure munin-node network access
  register: munin_node_conf_cidr_allow
  lineinfile:
    dest: /etc/munin/munin-node.conf
    line: "cidr_allow {{ hostvars[master_hostname].ansible_default_ipv4.address }}/32"

- name: install PostgreSQL plugin
  when: master_node
  register: munin_postres
  file:
    src: /usr/share/munin/plugins/{{ item.src }}
    path: /etc/munin/plugins/{{ item.dst or item.src }}
    state: link
    owner: root
    group: root
    mode: 0755
  with_items:
    - src: postgres_autovacuum
      dst: postgres_autovacuum
    - src: postgres_bgwriter
      dst: postgres_bgwriter
    - src: postgres_checkpoints
      dst: postgres_checkpoints
    - src: postgres_connections_db
      dst: postgres_connections_db
    - src: postgres_users
      dst: postgres_users
    - src: postgres_xlog
      dst: postgres_xlog
    - src: postgres_connections_
      dst: postgres_connections_{{ database_name }}
    - src: postgres_cache_
      dst: postgres_cache_{{ database_name }}
    - src: postgres_locks_
      dst: postgres_locks_{{ database_name }}
    - src: postgres_oldest_prepared_xact_
      dst: postgres_oldest_prepared_xact_{{ database_name }}
    - src: postgres_prepared_xacts_
      dst: postgres_prepared_xacts_{{ database_name }}
    - src: postgres_querylength_
      dst: postgres_querylength_{{ database_name }}
    - src: postgres_scans_
      dst: postgres_scans_{{ database_name }}
    - src: postgres_size_
      dst: postgres_size_{{ database_name }}
    - src: postgres_streaming_
      dst: postgres_streaming_{{ database_name }}
    - src: postgres_transactions_
      dst: postgres_transactions_{{ database_name }}
    - src: postgres_tuples_
      dst: postgres_tuples_{{ database_name }}

- name: restart munin-node
  when: munin_node_conf_hostname.changed or munin_node_conf_cidr_allow.changed or munin_squad_plugins.changed or munin_squad_plugins_conf.changed or munin_postres.changed
  command: systemctl restart munin-node

- name: Install munin
  when: master_node
  apt:
    pkg: munin
    state: present
    update-cache: yes

- name: Configure munin
  when: master_node
  template:
    src: roles/squad/templates/munin.conf
    dest: /etc/munin/munin.conf
  register: munin_conf

- name: run munin on configurations changes
  when: 'master_node and (munin_conf.changed or munin_squad_plugins.changed or munin_squad_plugins_conf.changed)'
  command: runuser -u munin munin-cron
