#!/usr/bin/env python3

import os
import sys
import django


if __name__ == '__main__':
    os.environ.setdefault('SQUAD_EXTRA_SETTINGS', '{{install_base}}/linaro_ldap.py')
    os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'squad.settings')

    django.setup()
    from linaro_ldap_backends import LDAPUsernameBackend
    ldap_backend = LDAPUsernameBackend()
    ldap_backend.populate_user(sys.argv[1])

