- name: Initialize the Kubernetes cluster using kubeadm
  command: kubeadm init --apiserver-advertise-address="172.31.1.10" --apiserver-cert-extra-sans="172.31.1.10" --node-name kubemaster --pod-network-cidr=172.31.1.0/24
  when: installed is changed

- name: Create .kube folder
  become: false
  file:
    path: /home/vagrant/.kube
    state: directory

- name: Copy admin.conf file
  copy: remote_src=True src=/etc/kubernetes/admin.conf dest=/home/vagrant/.kube/config

- name: Change admin.conf owner
  file:
    path: /home/vagrant/.kube/config
    owner: vagrant
    group: vagrant

- name: Install calico pod network
  become: false
  command: kubectl apply -f https://docs.projectcalico.org/v3.10/manifests/calico.yaml

- name: Generate join command
  command: kubeadm token create --print-join-command
  register: join_command

- name: Copy join command to local file
  copy:
    dest: "/tmp/join_k8s_cluster"
    content: "{{ join_command.stdout_lines[0] }}"
  become: false
  delegate_to: localhost
