- name: Copy the join command to server location
  copy:
    src: "/tmp/join_k8s_cluster"
    dest: /tmp/join-command.sh
    mode: 0777
  become: false

- name: Join the node to cluster
  command: sh /tmp/join-command.sh
  args:
    creates: /etc/kubernetes/kubelet.conf
