- include_role:
    name: worker
    tasks_from: setup.yml
  when: upgrade_only is not defined

- include_role:
    name: worker
    tasks_from: skip_setup.yml
  when: upgrade_only is defined

- command: systemctl restart squad-worker.service
  name: restart squad-worker
  when: squad_worker_service.changed or install_squad.changed or settings.changed or environmentfile.changed or linaro_ldap_backends.changed or install_squad_linaro_plugins.changed
  changed_when: False

