#!/bin/sh
#
# Copyright (c) 2018 Linaro Limited
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; version 2 dated June,
# 1991.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#
# Plugin to monitor the SQUAD job queue

# for master node only
if ! systemctl is-enabled --quiet squad-listener 2>/dev/null; then
    exit
fi

with_queues() {
    rabbitmqctl list_queues | awk "/^(celery|reporting_queue)\s/ { $@ }"
}

if [ "$1" = "config" ]; then
    echo "graph_title Queue"
    echo 'graph_args --base 1000 -l 0'
    echo 'graph_vlabel Jobs'
    echo 'graph_category squad'
    echo 'graph_info Number of jobs in the queue'
    with_queues 'print($1 ".label", $1)'
else
    with_queues 'print($1 ".value", $2)'
fi
