#!/bin/sh
#
# Copyright (c) 2018 Linaro Limited
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; version 2 dated June,
# 1991.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#
# Plugin to monitor the throughput of the SQUAD workers

# for worker nodes only
if ! systemctl is-enabled --quiet squad-worker 2>/dev/null; then
    exit
fi

if [ "$1" = "config" ]; then
    echo "graph_title Jobs processed by worker"
    echo 'graph_args --base 1000 -l 0'
    echo 'graph_vlabel Number of processes'
    echo 'graph_category squad'
    echo 'graph_info Number of jobs processed in the last 5 minutes'
    echo 'jobs.label Jobs'
    echo 'jobs.draw AREASTACK'
else
    printf 'jobs.value '
    journalctl --unit squad-worker.service --no-pager --since '5m ago' | grep -c Task.*succeeded || true
fi
